# Generated by Django 3.2.7 on 2021-11-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20211124_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
