# Generated by Django 3.2.7 on 2021-11-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20211125_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='to_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='from_date',
            new_name='start_date',
        ),
    ]
